[package]
name = "spm"
version = "0.1.0"
authors = ["Gajo Petrovic <gajopetrovic@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0.17"
walkdir = "2"
