version: "3.9"

services:
  db-migration:
    env_file:
      - .env.dev

  rocket:
    build: .
    env_file:
      - .env.dev
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    command: ./target/debug/sprd-backend

  updater:
    build: .
    env_file:
      - .env.dev
    volumes:
      - ./:/app
    command: /app/bin/update.sh

  adminer:
    image: adminer
    restart: always
    ports:
      - 7070:8080

volumes:
  db:
    driver: local
  rapid:
