FROM rust:1.58.1-buster as builder

WORKDIR /app
COPY . .
RUN cargo build --release
RUN mkdir -p /out && cp target/release/sprd-backend /out/ && cp target/release/update /out/

FROM debian:buster-slim
RUN apt-get update && apt-get install -y libpq-dev && rm -rf /var/lib/apt/lists/*
COPY --from=builder /out/* /app

ENV ROCKET_ADDRESS=0.0.0.0
ENV ROCKET_PORT=80

CMD /app/sprd-backend